// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBVLp1nTOI6g7AtOhY-LAWLxqn4vQX3Zo',
    appId: '1:791440112405:web:f05df7cc567096e668c71c',
    messagingSenderId: '791440112405',
    projectId: 'project428app',
    authDomain: 'project428app.firebaseapp.com',
    storageBucket: 'project428app.firebasestorage.app',
    measurementId: 'G-DNNXX1B64T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSkZFIRBF0_axRryzr4kzgNL6asvPG7cA',
    appId: '1:791440112405:android:3d28716b77b95ad468c71c',
    messagingSenderId: '791440112405',
    projectId: 'project428app',
    storageBucket: 'project428app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBVLp1nTOI6g7AtOhY-LAWLxqn4vQX3Zo',
    appId: '1:791440112405:web:0a433edd4782047d68c71c',
    messagingSenderId: '791440112405',
    projectId: 'project428app',
    authDomain: 'project428app.firebaseapp.com',
    storageBucket: 'project428app.firebasestorage.app',
    measurementId: 'G-10DT6B05EW',
  );

}